### PR TITLE
Fixed an issue where tag length is more than the current View.

### PR DESCRIPTION
**Pull request by MVakas**
There is a problem, when the tag has a long text it goes out of the view. See the screenshot for reference. It has been fixed.
simulator screen shot 14-jun-2017 11 13 19 am

### CODE REVIEW

**Comment by Saraavana** [comment]
Hi MVakas, Thanks for highlighting the issue. 

I think it will be good to show the tag as full string by setting the maximum width for the entire collection and allowing the UICollectionView to scroll even horizontally, as specified in below snippet,

  
```
override var collectionViewContentSize: CGSize
{
   return CGSize(width: contentWidth + 110, height: contentHeight)
}
```

**Comment by MVakas** [comment]
You mean show the tag string on multiple lines if it exceeds the width of the collection view?
And expand tag's height?

**Comment by Saraavana** [comment]
No, only increasing the width of the UICollectionView frame. Neither by showing in multiple lines nor by increasing tag's height. As like the below gif,

**Comment by Saraavana** [comment]
Hi @MVakas, Thanks for pointing out the issue. Increasing the Tag Height for multi-line Tag will bring ununiformity among the tags. So, I have fixed the height of tags, but width of the CollectionView expands in accordance with the Tags size

**Pull request closed without merging**
